import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./context/AuthContext";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: {
    default:"Create Next App",
    template: "%s | MyApp",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <header>
            <div>
              <h1 className="text-cyan-800">Header</h1>
            </div>
          </header>
        {children}
        <footer>
          <div>
            <h1 className="text-cyan-800">My footer</h1>
          </div>
        </footer>
        </AuthProvider>
      </body>
    </html>
  );
}
